CMD_IDS = {
    "Identify": 0x0,
    "Identify Query": 0x1,
    "Trigger effect": 0x40,
    "Add Group": 0x0,
    "View group": 0x1,
    "Get group membership": 0x2,
    "Remove group": 0x3,
    "Remove all groups": 0x4,
    "Add group if identifying": 0x5,
    "Add Scene": 0x0,
    "View Scene": 0x1,
    "Remove Scene": 0x2,
    "Remove All Scenes": 0x3,
    "Store Scene": 0x4,
    "Recall Scene": 0x5,
    "Get Scene Membership": 0x6,
    "Enhanced Add Scene": 0x40,
    "Enhanced View Scene": 0x41,
    "Copy Scene": 0x42,
    "Off": 0x0,
    "On": 0x1,
    "Toggle": 0x2,
    "Off with effect": 0x40,
    "On with recall global scene": 0x41,
    "On with timed off": 0x42,
    "Move to Level": 0x0,
    "Move": 0x1,
    "Step": 0x2,
    "Stop": 0x3,
    "Move to Closest Frequency": 0x8,
    "Move to Hue": 0x0,
    "Move Hue": 0x1,
    "Step Hue": 0x2,
    "Move to Saturation": 0x3,
    "Move Saturation": 0x4,
    "Step Saturation": 0x5,
    "Move to Hue and Saturation": 0x6,
    "Move to Color": 0x7,
    "Move Color": 0x8,
    "Step Color": 0x9,
    "Move to Color Temperature": 0xa,
    "Enhanced Move to Hue": 0x40,
    "Enhanced Move Hue": 0x41,
    "Enhanced Step Hue": 0x42,
    "Enhanced Move to Hue and Saturation": 0x43,
    "Color Loop Set": 0x44,
    "Stop Move Step": 0x47,
    "Move Color Temperature": 0x4b,
    "Step Color Temperature": 0x4c,
    "Reset Alarm": 0x0,
    "Reset all alarms": 0x1,
    "Get Alarm": 0x2,
    "Reset alarm log": 0x3,
    "Lock Door": 0x0,
    "Unlock Door": 0x1,
    "Toggle": 0x2,
    "Unlock with Timeout": 0x3,
    "Get Log Record": 0x4,
    "Set PIN Code": 0x5,
    "Get PIN Code": 0x6,
    "Clear PIN Code": 0x7,
    "Clear All PIN Codes": 0x8,
    "Set User Status": 0x9,
    "Get User Status": 0xa,
    "Set Weekday Schedule": 0xb,
    "Get Weekday Schedule": 0xc,
    "Clear Weekday Schedule": 0xd,
    "Set Year Day Schedule": 0xe,
    "Get Year Day Schedule": 0xf,
    "Clear Year Day Schedule": 0x10,
    "Set Holiday Schedule": 0x11,
    "Get Holiday Schedule": 0x12,
    "Clear Holiday Schedule": 0x13,
    "Set User Type": 0x14,
    "Get User Type": 0x15,
    "Set RFID Code": 0x16,
    "Get RFID Code": 0x17,
    "Clear RFID Code": 0x18,
    "Clear All RFID Codes": 0x19
}